version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - SERVER_PORT=3001
      - SERVER_HOST=0.0.0.0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=ai_household_budge
      - DB_SSLMODE=disable
      - JWT_SECRET=your-secret-key-here
      - JWT_EXPIRATION_HOURS=24
      - API_KEY_HEADER=X-API-Key
      - API_KEYS=key1,key2,key3
      - LOG_LEVEL=debug
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ai_household_budge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "45432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
